# Generated by Django 4.2.5 on 2023-11-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
