# Generated by Django 4.2.5 on 2023-11-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
