# Generated by Django 4.2.5 on 2023-11-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_products_size_product_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='product_features',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/products'),
        ),
    ]
