# Generated by Django 4.2.5 on 2023-11-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_products_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_features',
            old_name='image',
            new_name='specific_item_image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_image',
            new_name='image',
        ),
    ]
