# Generated by Django 4.2.5 on 2023-11-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_address_alter_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='cart_products',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='ordered_products',
        ),
    ]
