# Generated by Django 4.2.5 on 2023-11-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_customuser'),
        ('cart', '0004_rename_product_cart_cart_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_products',
        ),
        migrations.AlterField(
            model_name='order',
            name='no_of_items',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order')),
                ('ordered_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
            ],
        ),
    ]
